[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
exclude = ["venv", ".venv", "build", "dist", "data", "old_*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
extend-ignore = ["E501"]  # Black handles long lines

[tool.ruff.lint.isort]
known-first-party = ["src", "doppelbot"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true

[tool.bandit]
skips = ["B101"]  # assert used; reconsider as needed
